apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-vcd
    control-plane: controller-manager
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capvcd-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-vcd
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-vcd
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /opt/vcloud/bin/cluster-api-provider-cloud-director
          env:
            - name: CAPVCD_SKIP_RDE
              value: '{{ .Values.skipRDE }}'
          image: '{{.Values.image.name}}:{{.Values.image.tag}}'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: '{{ .Values.resources.limits.cpu }}'
              memory: '{{ .Values.resources.limits.memory }}'
            requests:
              cpu: '{{ .Values.resources.requests.cpu }}'
              memory: '{{ .Values.resources.requests.memory }}'
          securityContext:
            allowPrivilegeEscalation: false
              {{- with .Values.securityContext }}
                {{- . | toYaml | nindent 12 }}
              {{- end }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      priorityClassName: '{{ .Values.priorityClass }}'
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
          {{- with .Values.podSecurityContext }}
            {{- . | toYaml | nindent 8 }}
          {{- end }}
      serviceAccountName: capvcd-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: capvcd-webhook-server-cert
