apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
