apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - capvcd-webhook-service.{{ .Release.Namespace }}.svc
  - capvcd-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capvcd-selfsigned-issuer
  secretName: capvcd-webhook-server-cert
