apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    control-plane: controller-manager
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-vcd
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-vcd
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /opt/vcloud/bin/cluster-api-provider-cloud-director
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- with .Values.resources }}
          limits:
            cpu: {{ .limits.cpu }}
            memory: {{ .limits.memory }}
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
          {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/kubernetes/vcloud
          name: controller-manager-config-volume
      securityContext:
        runAsNonRoot: false
      serviceAccountName: capvcd-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: capvcd-webhook-server-cert
      - configMap:
          name: capvcd-manager-config
        name: controller-manager-config-volume
