apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    cluster.x-k8s.io/provider: infrastructure-vcd
    control-plane: controller-manager
