{{- if .Values.psps.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capvcd-controller-manager-psp
  labels:
  {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - capvcd-controller-manager-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capvcd-controller-manager-psp
  labels:
  {{- include "labels.common" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: capvcd-controller-manager
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: capvcd-controller-manager-psp
  apiGroup: rbac.authorization.k8s.io
{{- end }}
