apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/capvcd-serving-cert
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capvcd-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-vcdcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.vcdcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vcdclusters
  sideEffects: None