apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capvcd-leader-election-role
subjects:
- kind: ServiceAccount
  name: capvcd-controller-manager
  namespace: {{ .Release.Namespace }}