apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcd
    {{- include "labels.common" . | nindent 4 }}
  name: capvcd-controller-manager
  namespace: {{ .Release.Namespace }}