---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capvcd-serving-cert
  namespace: capvcd-system
spec:
  dnsNames:
    - capvcd-webhook-service.{{ .Release.Namespace }}.svc
    - capvcd-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: capvcd-webhook-server-cert
