# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "ignored" # not relevant as we are applying this patch to all CAPVCD CRDs via labelSelector
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
        - v1
      clientConfig:
        service:
          namespace: "{{ .Release.Namespace }}"
          name: capvcd-webhook-service
          path: /convert
