---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: monitoring-annotations
annotations:
  prometheus.io/scrape: "true"
  giantswarm.io/monitoring: "true"
  giantswarm.io/monitoring-port: "8080"
fieldSpecs:
  - path: metadata/labels
    create: true
    kind: Service
